// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'student_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

StudentInfo _$StudentInfoFromJson(Map<String, dynamic> json) => StudentInfo(
      thoiGianGetData: json['thoi_gian_get_data'] as String?,
      maSv: json['ma_sv'] as String?,
      tenDayDu: json['ten_day_du'] as String?,
      gioiTinh: json['gioi_tinh'] as String?,
      ngaySinh: json['ngay_sinh'] as String?,
      danToc: json['dan_toc'] as String?,
      tonGiao: json['ton_giao'] as String?,
      dienThoai: json['dien_thoai'] as String?,
      email: json['email'] as String?,
      dienThoai2: json['dien_thoai2'] as String?,
      email2: json['email2'] as String?,
      doiMatKhau: json['doi_mat_khau'] as bool?,
      soCmnd: json['so_cmnd'] as String?,
      lop: json['lop'] as String?,
      khuVuc: json['khu_vuc'] as String?,
      doiTuongUuTien: json['doi_tuong_uu_tien'] as String?,
      khoi: json['khoi'] as String?,
      nganh: json['nganh'] as String?,
      chuyenNganh: json['chuyen_nganh'] as String?,
      idChuyenNganh: json['id_chuyen_nganh'] as String?,
      khoa: json['khoa'] as String?,
      bacHeDaoTao: json['bac_he_dao_tao'] as String?,
      nienKhoa: json['nien_khoa'] as String?,
      maCvht: json['ma_cvht'] as String?,
      hoTenCvht: json['ho_ten_cvht'] as String?,
      emailCvht: json['email_cvht'] as String?,
      dienThoaiCvht: json['dien_thoai_cvht'] as String?,
      maCvhtNg2: json['ma_cvht_ng2'] as String?,
      hoTenCvhtNg2: json['ho_ten_cvht_ng2'] as String?,
      emailCvhtNg2: json['email_cvht_ng2'] as String?,
      dienThoaiCvhtNg2: json['dien_thoai_cvht_ng2'] as String?,
      maTruong: json['ma_truong'] as String?,
      tenTruong: json['ten_truong'] as String?,
      idDiaPhuong: json['id_dia_phuong'] as String?,
      idKhoa: json['id_khoa'] as String?,
      idSinhVien: json['id_sinh_vien'] as String?,
      idLop: json['id_lop'] as String?,
      idKhoi: json['id_khoi'] as String?,
      idBacHeNganh: json['id_bac_he_nganh'] as String?,
      idBacHe: json['id_bac_he'] as String?,
      idHe: json['id_he'] as String?,
      idQuyChe: json['id_quy_che'] as String?,
      idQuyCheP: json['id_quy_che_P'] as String?,
      idHocChe: json['id_hoc_che'] as String?,
      idDonViPhanCap: json['id_don_vi_phan_cap'] as String?,
      idCoSoLop: json['id_co_so_lop'] as String?,
      nhhkVao: json['nhhk_vao'] as int?,
      nhhkRa: json['nhhk_ra'] as int?,
      idLop2: json['id_lop2'] as String?,
      idKhoi2: json['id_khoi2'] as String?,
      idBacHeNganh2: json['id_bac_he_nganh2'] as String?,
      isMasterPass: json['is_master_pass'] as bool?,
      isCvhtDangNhap: json['is_cvht_dang_nhap'] as bool?,
      isPhuHuynhDangNhap: json['is_phu_huynh_dang_nhap'] as bool?,
      intHienDienSv: json['int_hien_dien_sv'] as int?,
      hienDienSv: json['hien_dien_sv'] as String?,
      intHienDienDkmh: json['int_hien_dien_dkmh'] as int?,
      dsMenuCamXem: json['ds_menu_cam_xem'] as List<dynamic>?,
      strHoanThanhDgrl: json['str_hoan_thanh_dgrl'] as String?,
      urlNetweb: json['url_netweb'] as String?,
    );

Map<String, dynamic> _$StudentInfoToJson(StudentInfo instance) =>
    <String, dynamic>{
      'thoi_gian_get_data': instance.thoiGianGetData,
      'ma_sv': instance.maSv,
      'ten_day_du': instance.tenDayDu,
      'gioi_tinh': instance.gioiTinh,
      'ngay_sinh': instance.ngaySinh,
      'dan_toc': instance.danToc,
      'ton_giao': instance.tonGiao,
      'dien_thoai': instance.dienThoai,
      'email': instance.email,
      'dien_thoai2': instance.dienThoai2,
      'email2': instance.email2,
      'doi_mat_khau': instance.doiMatKhau,
      'so_cmnd': instance.soCmnd,
      'lop': instance.lop,
      'khu_vuc': instance.khuVuc,
      'doi_tuong_uu_tien': instance.doiTuongUuTien,
      'khoi': instance.khoi,
      'nganh': instance.nganh,
      'chuyen_nganh': instance.chuyenNganh,
      'id_chuyen_nganh': instance.idChuyenNganh,
      'khoa': instance.khoa,
      'bac_he_dao_tao': instance.bacHeDaoTao,
      'nien_khoa': instance.nienKhoa,
      'ma_cvht': instance.maCvht,
      'ho_ten_cvht': instance.hoTenCvht,
      'email_cvht': instance.emailCvht,
      'dien_thoai_cvht': instance.dienThoaiCvht,
      'ma_cvht_ng2': instance.maCvhtNg2,
      'ho_ten_cvht_ng2': instance.hoTenCvhtNg2,
      'email_cvht_ng2': instance.emailCvhtNg2,
      'dien_thoai_cvht_ng2': instance.dienThoaiCvhtNg2,
      'ma_truong': instance.maTruong,
      'ten_truong': instance.tenTruong,
      'id_dia_phuong': instance.idDiaPhuong,
      'id_khoa': instance.idKhoa,
      'id_sinh_vien': instance.idSinhVien,
      'id_lop': instance.idLop,
      'id_khoi': instance.idKhoi,
      'id_bac_he_nganh': instance.idBacHeNganh,
      'id_bac_he': instance.idBacHe,
      'id_he': instance.idHe,
      'id_quy_che': instance.idQuyChe,
      'id_quy_che_P': instance.idQuyCheP,
      'id_hoc_che': instance.idHocChe,
      'id_don_vi_phan_cap': instance.idDonViPhanCap,
      'id_co_so_lop': instance.idCoSoLop,
      'nhhk_vao': instance.nhhkVao,
      'nhhk_ra': instance.nhhkRa,
      'id_lop2': instance.idLop2,
      'id_khoi2': instance.idKhoi2,
      'id_bac_he_nganh2': instance.idBacHeNganh2,
      'is_master_pass': instance.isMasterPass,
      'is_cvht_dang_nhap': instance.isCvhtDangNhap,
      'is_phu_huynh_dang_nhap': instance.isPhuHuynhDangNhap,
      'int_hien_dien_sv': instance.intHienDienSv,
      'hien_dien_sv': instance.hienDienSv,
      'int_hien_dien_dkmh': instance.intHienDienDkmh,
      'ds_menu_cam_xem': instance.dsMenuCamXem,
      'str_hoan_thanh_dgrl': instance.strHoanThanhDgrl,
      'url_netweb': instance.urlNetweb,
    };
